### PR TITLE
Login page ui 94

### PR DESCRIPTION
**Pull request by domludera**
Updated Login Page for UI to reflect mockups. #94 

Additionally, created primary palette and accent palette for ALTA with the help of @meshgin

### CODE REVIEW

**Comment by domludera** [comment]
npm i and ng serve work without an issue on my end, so not sure why the build_client is failing

**Comment by domludera** [comment]
'client/src/app/components/client-gridview/client-gridview.component.css' should be deleted, the merge will introduce the same file in .scss

**Comment by daphneaugier** [comment]
Capture d’écran 2020-10-31 à 20 38 54
Getting errors relating to the theming you created. Apparently, it cannot import the @alta-primary

**Comment by daphneaugier** [comment]
It compiles now! Well done for fixing the bug. 
Just an extra detail, on the mockups it says that the user logs in with '_email address_'. Here you wrote that the user should input '_username_'. Maybe you could change that so it fits the mockups! Other than that we're goooooood toooo goooooooooooo

**Comment by domludera** [comment]
It does indeed specify 'email address' in the mockups however, 'username' was already defined in the form labels

**Comment by NicholasNagy** [comment]
Actually @daphneaugier , currently you need to log in using a username.
The functionality right now in the backend is linked to that, but feel free to open a bug, since we're not actually supposed to have any usernames whatsoever.

Also @domludera , where did you branch off to make this PR? On master we don't have the register functionality anymore. It was a bug that makram removed recently. We shouldn't be exposing the register functionality to everyone.

Also, I think the buttons across the app have a different color from the primary color. Maybe we can use a variable for that?

**Comment by NicholasNagy** [comment]
Also, @domludera , please add a high-level description to your pull request of what you're adding and please link to the related issue.

**Comment by domludera** [comment]
@NicholasNagy I pulled from master, I spoke with @makchamp and he showed me how to toggle back and forth between opening the registration, I forgot to switch it back to false. I double checked the colors @meshgin she provided me with a color palette. We can define as many color palettes as we want, therefore even if we have different button colors from the primary color we'll still be able to cover it

**Review by NicholasNagy — COMMENTED** [review]
Everything looks pretty good and well formatted.
All that's left to do is fix that merge conflict. DM me on discord if you have any questions.

Once the conflict is fixed, I will merge.

**Review by NicholasNagy — APPROVED** [review]
Alright, everything looks good, I will merge it.

**Pull request merged**
