### PR TITLE
System (end-to-end) testing setup and conforming acceptance tests for Epic 1

### PR DESCRIPTION
**Pull request by makchamp**
####  - Tool used for e2e testing : JASMINE + Protractor 
Protractor comes packaged with angular. This tool runs selenium engine and allows for complete automation of the chrome browser. In other words it simulates a user’s interaction with an Angular application running in a browser or mobile device.
https://www.protractortest.org/#/infrastructure

#### - Setup environment to run the tests
Since these tests require data to be created, edited and persisted in a database for the duration of the tests, I needed to find a way to prepopulate and flush a test database before and after each test run. There is no direct way for protractor to communicate with django unless done through an API. To avoid extending the api simply for managing these tests, I chose to write a bash script to automate the process.

To run the end-to-end tests (from the root ALTA directory):
**script/e2e**

It will do everything required (no need for any manual configuration)
First it will populate a 'alta_test' database with the values from user fixtures
Then it will run the angular protractor e2e tests
Upon finishing, the test database will be flushed and the django server running on port 8000 will be killed.

#### - Included System tests that conform to the acceptance tests for Epic 1
- AT-1.1: System administrator creates a system administrator account #129
- AT-1.2: System administrator modifies their account information #130 
- AT-1.3: System administrator manages organizations #133 
-  AT-1.4: System administrator create organization's employee's accounts #134 
-  AT-1.5: System administrator modifies an organization's employee's account information #135 
- AT-1.6: System administrator modifies an organization's employee's account status #136

The tests should conform very closely to the acceptance criterias. However they do not deviate much beyond them.
The tests use a Page Object Model. This simply means each page in the app will have its own po file which includes all functions responsible for extracting elements from the DOM. This greatly improves readability, maintainability and reduces code duplication.
Also to note, the order of the tests is very important. I tried as much as possible to decouple the tests (further work might be needed on that front). The order is set in the file _'protractor.conf.js'_

#### - Miscellaneous 
- Created an env variable for the root url of the django api. Extracted all instances where it is used.
- Added user fixtures (users.json) as mentioned above:
This fixture can have many purposes. These users can be used in unit tests as test users (instead of having to type them out manually like we've been doing)
Also they can be inserted in the database, which is useful for system tests (as we need initial users in the database to perform the tests)

       To insert them in the database run the command:
       python manage.py loaddata users.json

        These users were created from the app and then the data was dumped to the file like so:
        python manage.py dumpdata user_account.customuser --indent 4 > users.json

- There is a 1 second delay between the tests. This is mainly done for visualization purposes but I also noticed that it has the added benefit of allowing pages to completely load before transitioning to the next test (prevents errors)
 - Fixed a couple bugs including disabling in the profile settings the first name and last name input fields (since they cant be changed) and allowing the email to be changed.

e2e_preview

### CODE REVIEW

**Comment by Neeham** [comment]
Excellent job with the script! The script works perfectly fine however on Windows the source path needs to be changed.

Since this script is based on linux the activate file in venv path is as follow: 

/venv/**bin**/activate

On Windows the activate path in venv is the following:

/venv/**Scripts**/activate

For now, we can replicate 2 copies of e2e file and rename them as follow: e2eLinux and e2eWin specifying the 2 different respective path. In the future we can make a fully working windows script which also closes the open port 8000 upon termination like it does on Linux.

**Comment by makchamp** [comment]
> Excellent job with the script! The script works perfectly fine however on Windows the source path needs to be changed.
> 
> Since this script is based on linux the activate file in venv path is as follow:
> 
> /venv/**bin**/activate
> 
> On Windows the activate path in venv is the following:
> 
> /venv/**Scripts**/activate
> 
> For now, we can replicate 2 copies of e2e file and rename them as follow: e2eLinux and e2eWin specifying the 2 different respective path. In the future we can make a fully working windows script which also closes the open port 8000 upon termination like it does on Linux.

I added another script called 'e2e-win' for windows. Its still bash so its not fully compatible but later we can rewrite it in batch/powershell if we need to. I also changed how the django server is stopped so maybe it will work for you now.

**Comment by NicholasNagy** [comment]
Excellent job! Script works perfectly fine on Linux. For future sprint we can definitely make the script compatible on Windows as well.

**Review by NicholasNagy — APPROVED** [review]
Excellent job! Script works perfectly fine on Linux. For future sprint we can definitely make the script compatible on Windows as well.

**Pull request merged**
